{{- range $key, $definition := .Values.nfs }}
---
# PV {{ print $key }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{$definition.pvname}}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{$definition.storage}}
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: {{$definition.path}}
    server: {{$definition.server}}
  persistentVolumeReclaimPolicy: Retain
---
# PVC {{ print $key }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{$definition.pvname}}-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{$definition.storage}}
  volumeName: {{$definition.pvname}}
  storageClassName: ""
{{- end }}