---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.nfs.raster.pvname}}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{.Values.nfs.raster.storage}}
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: {{.Values.nfs.raster.path}}
    server: {{.Values.nfs.raster.server}}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.nfs.raster.pvname}}-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.nfs.raster.storage}}
  volumeName: {{.Values.nfs.raster.pvname}}
  storageClassName: ""
