---
apiVersion: v1
data:
  hostname: {{ printf "172.17.0.1" | b64enc }}
  username: {{ printf "ogscloudconfig" | b64enc }}
  port: {{ printf "5432" | b64enc }}
  password: {{ printf "password" | b64enc }}

kind: Secret
type: Opaque
metadata:
  name: "ogscloud-database"

---
apiVersion: v1
data:
  database: {{ printf "swissre" | b64enc }}
  hostname: {{ printf "172.17.0.1" | b64enc }}
  username: {{ printf "backenduser" | b64enc }}
  port: {{ printf "5432" | b64enc }}
  password: {{ printf "1234" | b64enc }}
  schema: {{ printf "flicc" | b64enc }}

kind: Secret
type: Opaque
metadata:
  name: "geodata-database"

---
apiVersion: v1
data:
  username: {{ printf "ogscloudconfig" | b64enc }}
  password: {{ printf "password" | b64enc }}
  url: {{ printf "jdbc:postgresql://172.17.0.1:5432/ogscloud?currentSchema=config" | b64enc }}

kind: Secret
type: Opaque
metadata:
  name: "database-flicc"