apiVersion: v1
data:
  hostname: {{ printf "10.236.1.3" | b64enc }}
  username: {{ printf "ogscloudconfig" | b64enc }}
  port: {{ printf "5432" | b64enc }}
  password: {{ printf "password" | b64enc }}

kind: Secret
type: Opaque
metadata:
  name: "ogscloud-database"
